import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductService {
  flatobj: any = {};
  productdetails = [
    { id: 100000, type: 'firstcarousel', image: '100000.jpg' },
    { id: 100001, type: 'firstcarousel', image: '100001.jpg' },
    { id: 100002, type: 'firstcarousel', image: '100002.jpg' },
    { id: 100003, type: 'firstcarousel', image: '100003.jpg' },
    { id: 100004, type: 'firstcarousel', image: '100004.jpg' },
    { id: 100005, type: 'firstcarousel', image: '100005.jpg' },
    { id: 100006, type: 'firstcarousel', image: '100006.jpg' },
    { id: 100007, type: 'firstcarousel', image: '100003.jpg' },


    { id: 100008, image: '100008.jpg', type: 'firstrow-firstpart', item: 'Ac LG1.5', description: 'LG 1.5 Ton 3 Star Ac ', name: 'LG 1.5 Ton 3 Star DUAL Inverter Split AC(Copper ,AI Convertable 6-in-1 Cooling, 2 Way Swing, HD Filter with Anti-Virus Protection, Faster Cooling & Energy Saving,2024 Model, TS-Q18JNXE3, White)', store: 'LG', price: 43990, reviews: 2579, deliveringplace: 'Bengaluru', pincode: 560108, add: '5 in 1 Convertable ACs with AI Pro', discountableprice: 75000, warrenty: 1, availability: 'Unavailable', brand: 'LG', color: 'white', itemweight: 100, material: 'Aluminium,Copper', SpecialFeature: ' Oscillating air vanes for dissipation of cold air', About: ' Split AC with inverter compressor: Variable speed compressor which adjusts power depending on heat load. AI 6-in1 Convertible feature with 6 cooling modes allows for flexible temperature control by operating in different tonnages by adjusting cooling capacity (40% to 110%) to match different needs basis room size or occupancy, enhancing energy efficiency and providing personalized comfort with minimal effort (T&C Apply- *Maximum Cooling Capacity may vary from model to model between 110% to 116%.) • Capacity: 1 Ton. Suitable for Small Sized Rooms (110 to 120 sq. ft.) | 425/989 (In/Out) CFM Air Circulation, Cooling Capacity 3470 W & Ambient Temperature: 52 degree Celsius with 4 way air swing • Energy Rating: 4 Star - High energy efficiency | Annual Energy Consumption: 571.99 Units | ISEER Value: 4.7 (Please Refer Energy Label on Product Page or Contact Brand for More Details) •  Manufacturer Warranty: 1 Year on product, 5 Years on PCB and 10 Years on Compressor with Gas Charging (T&C Apply) • Condenser Coil: Copper With Ocean Black Protection prevents From Rust & Corrosion; Increase Durability ; Uninterrupted Cooling • Key Features: Dual Inverter Compressor, AI Convertible 6-in-1 Cooling, VIRAAT Mode, HD Filter with Anti-Virus Protection, ADC Sensor, Cools at 52⁰ C, Stabilizer free operation within 120V-290V voltage range , Magic Display for temperature, Noise Level: IDU - 21 (db) & ODU – 51 (db) • Special Features: Gold Fin+ - Increase durability, Ocean black protection, Ez Clean Filter, Low gas detection, 100% Copper Condensor, 6 Fan Speed steps; Hi grooved Copper; Smart Diagnosis System, Comfort Air, Monsoon Comfort/Fresh Dry, Auto Clean, Mute, On/ Off Timer, Sleep Mode, Auto Restart (Memory), On/Off Indicator, Dehumidifier' },
    { id: 100010, image: '100010.jpg', type: 'firstrow-firstpart', item: 'Ac LG', description: 'LG 1 Ton 4 Star Ac', name: 'LG 1 Ton 4 Star DUAL Inverter Split AC (Copper, AI Convertible 6-in-1 Cooling, 4 Way Swing, HD Filter with Anti-Virus Protection, Faster Cooling & Energy Saving, 2024 Model, TS-Q13JNYE, White)', store: 'LG', price: 35790, reviews: 2518, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Godrej 1.5 Ton 5 star, 5 Years Comprehensive Warrenty', discountableprice: 54900, warrenty: 1, availability: 'available', brand: 'LG', color: 'white', itemweight: 110, material: 'Aluminium,Copper', SpecialFeature: ' Oscillating air vanes for dissipation of cold air', About: ' Split AC with inverter compressor: Variable speed compressor which adjusts power depending on heat load. AI 6-in1 Convertible feature with 6 cooling modes allows for flexible temperature control by operating in different tonnages by adjusting cooling capacity (40% to 110%) to match different needs basis room size or occupancy, enhancing energy efficiency and providing personalized comfort with minimal effort (T&C Apply- *Maximum Cooling Capacity may vary from model to model between 110% to 116%.) • Capacity: 1 Ton. Suitable for Small Sized Rooms (110 to 120 sq. ft.) | 425/989 (In/Out) CFM Air Circulation, Cooling Capacity 3470 W & Ambient Temperature: 52 degree Celsius with 4 way air swing • Energy Rating: 4 Star - High energy efficiency | Annual Energy Consumption: 571.99 Units | ISEER Value: 4.7 (Please Refer Energy Label on Product Page or Contact Brand for More Details) •  Manufacturer Warranty: 1 Year on product, 5 Years on PCB and 10 Years on Compressor with Gas Charging (T&C Apply) • Condenser Coil: Copper With Ocean Black Protection prevents From Rust & Corrosion; Increase Durability ; Uninterrupted Cooling • Key Features: Dual Inverter Compressor, AI Convertible 6-in-1 Cooling, VIRAAT Mode, HD Filter with Anti-Virus Protection, ADC Sensor, Cools at 52⁰ C, Stabilizer free operation within 120V-290V voltage range , Magic Display for temperature, Noise Level: IDU - 21 (db) & ODU – 51 (db) • Special Features: Gold Fin+ - Increase durability, Ocean black protection, Ez Clean Filter, Low gas detection, 100% Copper Condensor, 6 Fan Speed steps; Hi grooved Copper; Smart Diagnosis System, Comfort Air, Monsoon Comfort/Fresh Dry, Auto Clean, Mute, On/ Off Timer, Sleep Mode, Auto Restart (Memory), On/Off Indicator, Dehumidifier' },
    { id: 100011, image: '100011.jpg', type: 'firstrow-firstpart', item: 'Ac Panasonic', description: 'Panasonic 1.5 Ton 3 Star ', name: 'Panasonic 1.5 Ton 3 Star Wi-Fi Inverter Smart Split AC (Copper Condenser, 7 in 1 Convertible with True AI Mode, PM 0.1 Air Purification Filter, CS/CU-SU18ZKYWT, 2024 Model, White)', store: 'panasonic', price: 35990, reviews: 3688, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Godrej 1.4 Ton 5 star, 5 Years Comprehensive Warrenty', discountableprice: 49900, warrenty: 1, availability: 'Unavailable', brand: 'Panasonic', color: 'white', itemweight: 120, material: 'Aluminium', SpecialFeature: ' Oscillating air vanes for dissipation of cold air', About: '7 in 1 Convertible Modes with True AI Mode (converti7): True AI mode smartly detects the rooms temperature forecast the cooling capacity and change the fan speed to provide optimal cooling through inbuilt sensors and artificial intelligence. Save energy with adjustment of cooling performance by selecting modes ranging from 40% to 90%, Full capacity and High capacity) • Capacity: 1.5 Ton - Suitable for medium sized rooms (121-170 sq ft). Energy Star Rating: 3 Star | Annual Power Consumption: 1002.31 kWh | ISEER: 3.90. The star rating is as per new BEE guidelines.501 (Indoor) CFM Air Circulation & Ambient Temperature: 16 to 52 degree Celsius • Energy Rating: 4 Star - High energy efficiency | Annual Energy Consumption: 571.99 Units | ISEER Value: 4.7 (Please Refer Energy Label on Product Page or Contact Brand for More Details) •  Manufacturer Warranty: 1 Year on product, 5 Years on PCB and 10 Years on Compressor with Gas Charging (T&C Apply) • Condenser Coil: Copper With Ocean Black Protection prevents From Rust & Corrosion; Increase Durability ; Uninterrupted Cooling • Key Features: Dual Inverter Compressor, AI Convertible 6-in-1 Cooling, VIRAAT Mode, HD Filter with Anti-Virus Protection, ADC Sensor, Cools at 52⁰ C, Stabilizer free operation within 120V-290V voltage range , Magic Display for temperature, Noise Level: IDU - 21 (db) & ODU – 51 (db) • Special Features: Gold Fin+ - Increase durability, Ocean black protection, Ez Clean Filter, Low gas detection, 100% Copper Condensor, 6 Fan Speed steps; Hi grooved Copper; Smart Diagnosis System, Comfort Air, Monsoon Comfort/Fresh Dry, Auto Clean, Mute, On/ Off Timer, Sleep Mode, Auto Restart (Memory), On/Off Indicator, Dehumidifier' },
    { id: 100012, image: '100012.jpg', type: 'firstrow-firstpart', item: 'Ac Daikin', description: 'Daikin 1.5 Ton 3 Star Inverter Split AC ', name: 'Daikin 1.5 Ton 3 Star Inverter Split AC (Copper, PM 2.5 Filter, Triple Display, Dew Clean Technology, Coanda Airflow, 2024 Model, MTKL50U, White)', store: 'Daikin', price: 36990, reviews: 3685, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Godrej 1.4 Ton 5 star, 5 Years Comprehensive Warrenty', discountableprice: 49900, warrenty: 1, availability: 'available', brand: 'Daikin', color: 'white', itemweight: 130, material: 'Aluminium,Copper', SpecialFeature: 'High Ambient Operation upto 52C,3D Airflow,Dew Clean', About: ' split ac with inverter swing compressor and hepta sense: dew clean technology; triple display; pm 2.5 filter to ensure healthy air • capacity 1.5 ton: suitable for small sized rooms (111 to 150 sq.ft); 572 cfm with an air throw of 16 meters • 3 star: energy efficiency •  warranty: 1 years on product, 5 years on pcb, 10 years on compressor • Condenser Coil: Copper With Ocean Black Protection prevents From Rust & Corrosion; Increase Durability ; Uninterrupted Cooling • Key Features: Dual Inverter Compressor, AI Convertible 6-in-1 Cooling, VIRAAT Mode, HD Filter with Anti-Virus Protection, ADC Sensor, Cools at 52⁰ C, Stabilizer free operation within 120V-290V voltage range , Magic Display for temperature, Noise Level: IDU - 21 (db) & ODU – 51 (db) • Special Features: Gold Fin+ - Increase durability, Ocean black protection, Ez Clean Filter, Low gas detection, 100% Copper Condensor, 6 Fan Speed steps; Hi grooved Copper; Smart Diagnosis System, Comfort Air, Monsoon Comfort/Fresh Dry, Auto Clean, Mute, On/ Off Timer, Sleep Mode, Auto Restart (Memory), On/Off Indicator, Dehumidifier' },

    { id: 100013, image: '100013.jpg', type: 'firstrow-secondpart', item: 'fan', description: 'Bajaj Frore Neo 400 ', name: 'Bajaj Frore Neo 400 MM Oscillating Pedestal Fan for Home|Aerodynamically Balanced Blades| 100% CopperMotor| HighAir Delivery|3-Speed Control| Rust Free|2-Yr Warranty Red', store: 'Bajaj', price: 2409, reviews: 283, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Orpat BLDC Cieling fan Moneysaver Genz 28W With Remote', discountableprice: 3699, warrenty: '6 months', availability: 'available', brand: 'Bajaj', color: 'red', itemweight: 4, material: 'Aluminium', SpecialFeature: ' Oscillating', About: ' TYPE: Pedestal Fan; SERIES: Bajaj Frore Neo; SWEEP: 400mm, HIGH SPEED: 1350 RPM, AIR DELIVERY: 65CMM, POWER: 55 W; COLOUR: Scarlet Red • WARRANTY: Product Warranty By Bajaj Electricals Limited- 2 years. Terms & Conditions Applied • 100% COPPER MOTOR & STRONG BASE: The fan comes with 100% Copper Motor for longer life & consistent Performance & have Sturdy and Strong Base for Better Stability of the Product • OVERLOAD PROTECTOR: Bajaj Frore Neo Pedestal Fan is equipped with Built in Thermal Overload Protector to Protects Motor from Voltage Surge • SPEED CONTROL & RUST FREE BODY: Fan is provided with 3 Speed Regulation for convenient operations. The Rust Free Body of the Pedestal Fan ensure enhanced longevity •CONSUMER SUPPORT - Reach out to Bajaj Consumer Care for any warranty issues/service. Free home service available under product warranty period. T & C Applied' },
    { id: 100014, image: '100014.jpg', type: 'firstrow-secondpart', item: 'earbuds', description: 'Redmi Buds 4 Active ', name: 'Redmi Buds 4 Active - Bass Black, 12mm Drivers(Premium Sound Quality), Up to 30 Hours Battery Life, Google Fast Pair, IPX4, Bluetooth 5.3, ENC, Up to 60ms Low Latency Mode, App Support', store: 'Redmi', price: 1399, reviews: 28541, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Boult Audio z40 True Wireless', discountableprice: 4999, warrenty: 1, availability: 'available', brand: 'Redmi', color: 'Black', itemweight: 400, material: 'plastic, metal, silicone', SpecialFeature: 'True wireless', About: ' Rise, Never Fall. • Drivers: The powerful 12mm Bass Pro drivers, designed to deliver an immersive audio experience with deep, rich bass and crisp, clear highs • Battery: Unleash the freedom of extended usage with upto an astounding 30 hours of battery life. Our innovative technology ensures that you can enjoy uninterrupted music, podcasts, and calls throughout the day, without worrying about running out of power. • ENC: Enjoy crystal-clear conversations even in noisy environments, as the powerful mic captures your voice with remarkable clarity while Environmental Noise Cancellation (ENC) actively reduces background noise for an uninterrupted and immersive calling experience. Stay connected and communicate effortlessly with our premium audio solution. • Google Fast Pair: In one tap, the Redmi Buds 4 Active enables quick, effortless Bluetooth pairing with your Android* devices. You can even check to see where you last placed it. • Fast Charging: Designed to keep up with your active lifestyle, our Redmi Buds 4 Active offers rapid charging capabilities that get you upto 90 minutes of playback time in just 10 minutes.' },
    { id: 100015, image: '100015.jpg', type: 'firstrow-secondpart', item: 'Floor Mat', description: 'PRIMESKY Bathroom Floor Mat ', name: 'PRIMESKY Bathroom Floor Mat Water Absorbing Mat For Quick Dry Rubber Backed Anti-Slip Rectangular Shape Floor Mat Non Slip Mat For Home Kitchen (40 X 60 Cm) (2)', store: 'PRIMESKY', price: 449, reviews: 1170, deliveringplace: 'Bengaluru', pincode: 560108, add: 'super soft anti slip bath mats my luxe home', discountableprice: 1799, warrenty: '3 months', availability: 'available', brand: 'PRIMESKY', color: 'Gray', itemweight: '440 grams', material: 'Rubber', SpecialFeature: ' Weave Type Flat Woven', About: ' COMFORT AND CARE IN MIND - Our bathmats are luxury mats that have been made with your comfort and care in mind. They are extremely soft and have a plush feel to them; they are also quite absorbent and will keep your feet toasty and snugly dry. This bathroom mats enticing designs will give your bathroom a fresh look. Bathmats are the ideal combination of comfort and design for refreshing your bathroom • Capacity: 1 Ton. Suitable for Small Sized Rooms (110 to 120 sq. ft.) | 425/989 (In/Out) CFM Air Circulation, Cooling Capacity 3470 W & Ambient Temperature: 52 degree Celsius with 4 way air swing • MACHINE WASHABLE - This bathroom mat is machine washable, which makes it even more convenient. Simply toss this washable bathroom mat into your washing machine on a mild cycle and hang to dry or let it air dry. Wash in a machine with cold water and a light detergent. Neither chlorine nor bleach should be used. •  Performance - The mats anti-skid latex backing keeps it in place even when wet. When utilised for children/kids or elderly, the durable non-slip backing will not fade and will provide piece of mind.' },
    { id: 100016, image: '100016.jpg', type: 'firstrow-secondpart', item: 'helmet', description: 'Vega Crux ISI Flip-Up Helmet ', name: 'Vega Crux ISI Certified Flip-Up Helmet for Men and Women with Clear Visor(Black, Size:M)', store: 'Vega', price: 1163, reviews: 51545, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Vega Crux Dx Black Helmet', discountableprice: 1550, warrenty: 1, availability: 'available', brand: 'Vega', color: 'Black', itemweight: '1.49 kg', material: 'Acrylonitrile Butadiene Styrene (ABS)', SpecialFeature: 'Off-road', About: ' The Helmet size would be: Extra Small (54 cm), Small (56 cm), Medium (57 cm), and Large (58 cm), ensuring a perfect fit for different head sizes. • Material: The helmet has a High Impact ABS material shell, offering durability and protection. Certification: It is ISI Certified, confirming it meets safety standards. • Weight: Weighs 1100 grams, slightly heavier but still comfortable. Lining: Features a removable, washable, and odor-resistant lining, helping to keep the helmet fresh for longer between cleanings. •  Buckle: Comes with a metallic quick-release silent buckle for easy fastening and removal. Visor: The visor is scratch-resistant and UV-resistant, made from optical polycarbonate, and includes a quick-release mechanism for smooth and easy visor changes.' },

    { id: 100017, image: '100017.jpg', type: 'firstrow-thirdpart', item: 'Bed sheet', description: 'Layers Savona Cotton  ', name: 'Layers Savona Cotton Micro Poly TC Double Reversible Comforter (Red Coral)', store: 'Layers', price: 2499, reviews: 25, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Premium Comfortable from solimo', discountableprice: 3999, warrenty: 1, availability: 'available', brand: 'Layers', color: 'Red & Coral', itemweight: '2.74L x 2.28W Meters', material: 'Cotton', SpecialFeature: ' Skin Friendly, Lightweight, Breathable', About: ' Package Includes: 1 Double Comforter | Comforter: 2.74 m x 2.28 m •Thread Count: MICRO POLY TC, Fits perfectly on a Regular sized Double Bed • Material: Cotton. Natural and guilt free cotton make these bedsheets safe & comfortable for every season. Cotton is skin friendly, light weight and breathable, adding value to your sleep experience. Its moisture absorbent property and easy to maintain attribute, make it more desirable. • Our textiles are engineered to create the most balanced construction of fabric which makes our Comforters breathable, moisture absorbent, light weight, cool and crisp in their feel. These 100 % cotton bedsheets and comforters are made using skin friendly dyes safe for everyday use. The breathable fabric makes is a perfect sleep option. • Easy to Wash: Our Comforters are machine washable (40 degrees), easy to maintain & color fast. However use of mild detergent is advisable. Avoiding hard brushing will improve product life.' },
    { id: 100018, image: '100018.jpg', type: 'firstrow-thirdpart', item: 'Home Decor', description: 'Home Decorator ', name: 'Street27 Polyvinyl Chloride 3Pcs Astronaut Action Figurine Home Decor Astronaut Statue Study Office Desk Decor Showpiece Gift Decoration Accessories Outer Space Pvc Sculpture(Golden)', store: 'Street27', price: 397, reviews: 1139, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Define Art pedestal Statue Base for Figurine  idol& showpiece', discountableprice: 1599, warrenty: '6 months', availability: 'available', brand: 'street27', color: 'Multicolor', itemweight: '450g', material: 'Polyvinyl Chloride', SpecialFeature: 'Can be displaying at bookshelf, fireplace', About: ' 3 Pieces Astronaut Statue Figurine Ornament Space Man Sculpture Decoration Crafts Arts •Astronaut design is adorable and attractive as a gift for children, kids, friends, sons, daughters • Made of environmental PVC material, non-toxic, tasteless, safe and healthy and solid for using • Suitable for cake topper, interior home office decor, living room, bedroom, space theme decorating •Can be displaying at bookshelf, fireplace mantel, TV cabinet, windowsill, desktop, coffee table, shelf and more' },
    { id: 100019, image: '100019.jpg', type: 'firstrow-thirdpart', item: 'Wardrobe Organizer For Clothes', description: 'Wardrobe Organizer For Clothes ', name: 'HomeStrap Set Of 6 Non-Woven Printed Saree Cover/Cloth Storage/Wardrobe Organizer For Clothes With Transparent Window(Grey)(Shark Tank Featured),45 Cm,22 Cm', store: 'Homestrap', price: 341, reviews: 14772, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Kuber Industries Saree Storage', discountableprice: 75000, warrenty: 1, availability: 'Unavailable', brand: 'HomeStrap', color: 'Grey', itemweight: '1KG', material: 'Polypropylene', SpecialFeature: ' Lightweight, Stackable', About: 'MADE IN INDIA | Printed Saree Cover to organize your cluttered wardrobe. •Material: Heavy quality Non-Woven fabric to prevent your favorite Silk/Cotton Sarees from Dust, Moisture, and Moths. • Easily stacked one on top of the other, magically creating more space in your wardrobe, Avoid Creases in clothes • Dimension: Length(17.5 Inches), Width (13 Inches), Height (8.5 Inches) | Length( 45 CMs), Width ( 33.5 CMs), Height (22 CMs). • Comes with 2 Premium zippers with a Transparent Front window Keeping the clothes inside visible and easy to access.' },
    { id: 100020, image: '100020.jpg', type: 'firstrow-thirdpart', item: 'Decorative LED String Light', description: 'Decorative LED String Light', name: 'Quace 12 Meter Decorative 42 Warm White LED String Light Plug for Indoor & Outdoor Decorations,String Lights for DIY, Party, Home Decor, Christmas, Diwali', store: 'Quace', price: 79, reviews: 2418, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Litehom LED Net Mesh String Lights,9.8Ft X 6.6Ft, 192 LEDs', discountableprice: 1999, warrenty: 2, availability: 'available', brand: 'Quace', color: 'Warm white', itemweight: '100g', material: 'Metal,Copper', SpecialFeature: 'String', About: ' These lights can be bent skilfully to decorate and achieve a nice effect, but please be careful not to scrape the insulation off or cut the wires. • Warning: If the customer wants to connect multiple lights through a connector then the voltage of the connector must to be 220-240 volts, or else it would lead to a short circuit' },

    { id: 100021, image: '100021.jpg', type: 'firstrow-forthpart', item: 'Spin Mop', description: 'Steel Wringer Spin Mop ', name: 'Spotzero by Milton Prime Stainless Steel Wringer Spin Mop with Big Wheel, Puller Handle, Bucket Floor Cleaning and Mopping System 360° Flexible,2 Microfiber Refills, Big Size, Aqua Green', store: 'Spotzero By Milton Store', price: 1399, reviews: 92412, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Amazon Brand- Presto! Elite spin mope', discountableprice: 2158, warrenty: 1, availability: 'Unavailable', brand: 'Milton', color: '	Aqua Green', itemweight: '2.4kg', material: '	Plastic', SpecialFeature: 'Spin Mop', About: ' Package Contents: 1- Piece Prime spin mop set comes with 1 steel wringer mop bucket with 2 pcs big wheels; 1 stainless steel mop rod; 2 high quality microfiber mop refill; 1 Liquid Soap Dispenser •STURDY MOP WITH STEEL WRINGER FOR FLOOR CLEANING: A perfect blend of style and comfort, this popular cleaning tool comes with stainless steel wringer, big wheels, and a puller handle to help you clean every area in the house effortlessly. • BIG WHEELS AND PULLER HANDLE: Comes with 2pcs big wheels and puller to easily carry the bucket around the house. Makes home cleaning effortless and easy. •  360-DEGREE ROTATING SPIN MOP HANDLE: Light-weight and adjustable stainless-steel mop handle reaches corner of the house - like under the table, below the bed, very easily. • WATER OUTLET PLUG: The outlet carries out easy drainage of dirty water from the bucket without using your hands. • MICROFIBER POWER PERFORMANCE FOR FLOOR CLEANING WITH MAGIC MOP】: Microfiber material with its unique feature of deep cleaning helps lift and trap fine dust / dirt particles. Microfiber mop head is machine-washable and reusable. •LIQUID DISPENSER: Add cleaning solution to the water through specially designed liquid dispenser and leave your floors spick-and-span with a tinge of fragrance.' },
    { id: 100022, image: '100022.jpg', type: 'firstrow-forthpart', item: 'Bathroom Accessories-Stainless', description: 'Bathroom Accessories', name: 'Hindware Bathroom Accessories-Stainless Steel 304 Grade Folding Towel Rack for Bathroom', store: 'Hindware', price: 1722, reviews: 132, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Arena stainless steel folding', discountableprice: 3499, warrenty: 1.5, availability: 'Unavailable', brand: 'Hindware', color: 'Chrome', itemweight: '1.5 Kilograms', material: 'Stainless Steel', SpecialFeature: 'Polished', About: 'Premium Stainless Steel Construction: The Hindware Bathroom Accessories Folding Towel Rack is crafted from high-quality 304-grade stainless steel, ensuring not only a sleek and modern appearance but also durability and resistance to corrosion in the bathroom environment. • Space-Saving Folding Design: Featuring a practical folding mechanism, this towel rack optimizes space utilization. When not in use, simply fold it away to create more room in your bathroom. This design is especially convenient for bathrooms with limited space. •Versatile Towel Storage: With multiple bars, this rack provides ample space for hanging and drying towels. The thoughtful design allows you to neatly organize towels of various sizes, keeping your bathroom tidy and well-ordered. • Sleek and Modern Aesthetic: The contemporary design of the stainless steel towel rack adds a touch of elegance to your bathroom decor. The polished finish not only enhances its visual appeal but also makes it easy to clean and maintain, ensuring long-lasting beauty. • Easy Installation and Stability: The Hindware Folding Towel Rack comes with straightforward installation instructions, making it easy to set up. The sturdy construction ensures stability when towels are hung, providing a reliable and convenient storage solution for your bathroom.' },
    { id: 100023, image: '100023.jpg', type: 'firstrow-forthpart', item: 'Hammer', description: 'Buildskill Steel Shaft Hammer 8 Oz', name: 'Buildskill Steel Shaft Hammer 8 Oz - Forged Steel Head for Superior Strength & Durability - Carpenter Tools for Wood Work, Home and Professional, 2 in 1 Combination Claw & Flat Head, 400gm (Pack of 1)', store: 'BUILDSKILL', price: 208, reviews: 1045, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Homdum 13 inch Multipurpose', discountableprice: 648, warrenty: 1, availability: 'available', brand: 'BUILDSKILL', color: 'silver', itemweight: '1.5kg', material: 'Carbon Steel', SpecialFeature: ' Lightweight Yet Strong', About: 'Lightweight Yet Strong - Dont let its weight fool you! This tool retains a robust strength despite its lightweight handle. Its versatility makes it a must-have addition to your kit of hardware tools and wood working tools •Convenience is Key - Our Steel Shaft Hammer comes with a 2-in-1 claw and flat head, making it an all-purpose tool. Truly a fitting addition to your home tools collection or ideal for those in the industrial tools sector • Ergonomic Comfort - The tools handle is ergonomically designed, making continuous use easy and efficient. Its a small hammer that packs a punch, suitable for both home improvements and professional construction tools • Work Friendly Design - Perfect for all tasks, from small home fixes to major construction jobs. Melding comfort with functionality, this hammer is a standout among carpentry tools for wood work. Truly a versatile tool for home and beyond' },
    { id: 100024, image: '100024.jpg', type: 'firstrow-forthpart', item: ' Power Strip', description: 'GM 3060 E-Book 4 + 1 Power Strip', name: 'GM 3060 E-Book 4 + 1 Power Strip Red & White Color 250 Volts with Master Switch, Indicator, Safety Shutter & 4 International sockets, Extension Cord for Home Appliances', store: 'GM', price: 499, reviews: 617898, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Anchor by panasonic 4 way 6A international socket', discountableprice: 1226, warrenty: 1, availability: 'Unavailable', brand: 'GM', color: 'Mulitcolor', itemweight: '120g', material: 'Plastic', SpecialFeature: 'Verstile International sockets ', About: ' Verstile International sockets (with child safety shutter) The safety shutter keeps children safe & also prevents dust from getting into unsend sockets overtime. • 2 Meter Heavy duty cord A special nylon velcro cable tie has been provided on the long power cord for convenience during operation and storage. • Supply Indicator The Spike guard has an LED Supply indicator embedded in the ergonomic design that indicates power status if On/Off. •Novel & Distinctive design Combination of advanced mould design, unique exquisite workmanship & our commitment to perfection have rendered the product its excellent quality. • Safety shutdown technology It has Thermal overload trip to power off your system, which saves all connected devices in the event of a severe over current or when the surge protection is disable. You can press red button to return to safe function mode. Ergonomic design- Adequate space has been provided between the sockets for accommodating plugs of different designs. Suitable for household, office, computer and its Peripherals, DVD, T.V' },

    { id: 100025, image: '100025.jpg', type: 'secondraw-videoadd', title: 'Prime Video: Recommended for you', name: 'Little Krishna' },

    { id: 100026, image: '100026.jpg', title: 'Up to 75% off | Headphones', type: 'secondraw-secondpart', item: ' Earphone', name: 'OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass - 12.4 Mm Drivers, 10 Mins Charge - 20 Hrs Music, 30 Hrs Battery Life (Jazz Green)', store: 'OnePlus', price: 1499, reviews: 179889, deliveringplace: 'Bengaluru', pincode: 560108, add: '60H Playtime with zen ENC Mic, 10mm Bass Drivers', discountableprice: 4999, warrenty: 1, availability: 'available', brand: 'Oneplus', color: 'Green', itemweight: '250grame', material: 'Metal,Plastic', SpecialFeature: 'Sound Isolation', About: 'A quick 10-minute charge delivers up to 20 hours of immersive audio playback; The flagship-level battery life delivers up to 30 hours of non-stop music on a single charge • A large 12.4 mm bass driver delivers uncompromisingly deep bass for powerful beats. Experience incredibly rich audio detail at every frequency with the titanium coating dome. Codec: Supports AAC and SBC •Anti-distortion audio technology ensures your audio playtime stays silky-smooth. Thanks to the larger sound cavity and industry-leading algorithms, notes remain distortion-free • Water and sweat-resistant, the IP55-rated internals and design ensure your OnePlus Bullets Wireless Z2 stay all-weather ready • Condenser Coil: Copper With Ocean Black Protection prevents From Rust & Corrosion; Increase Durability ; Uninterrupted Cooling ' },

    { id: 100030, image: '100030.jpg', type: 'secondraw-thirdpart', item: 'men sport shoes', name: 'Puma Mens Dazzler Sneaker', store: 'puma', price: 1439, reviews: 6402, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Campus Mens mike running shoe', discountableprice: 3299, warrenty: 1, availability: 'available', brand: 'puma', color: 'black', itemweight: '600 g', material: 'Textile', SpecialFeature: 'Rubber', About: ' Style Name:-Sneaker • Model Name:-Dazzler • Brand Color:-PUMA Black-PUMA Silver • Wipe with a clean dry cloth' },
    { id: 100031, image: '100031.jpg', type: 'secondraw-thirdpart', item: 'men casual shoes ', name: 'Red Tape Mens Walking Shoes', store: 'Red Tape', price: 1424, reviews: 96, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Columbus CONTEST-04 casual shoes', discountableprice: 2399, warrenty: 1, availability: 'available', brand: 'Redtape', color: 'Black', itemweight: '650 g', material: 'Leather', SpecialFeature: 'Sole materialEthylene Vinyl Acetate', About: ' Closure:Lace-Up • Type:Walking Shoes • Upper Material:Textile • Sole Material:Eva • Care Instruction: Wipe with a clean, dry cloth to remove the dust.' },
    { id: 100032, image: '100032.jpg', type: 'secondraw-thirdpart', item: 'women shoe', name: 'Campus Womens Zoe Plus Walking Shoe', store: 'campus', price: 727, reviews: 3209, deliveringplace: 'Bengaluru', pincode: 560108, add: 'Asian womens firflety sport shoe', discountableprice: 1999, warrenty: 1, availability: 'available', brand: 'Campus', color: 'red', itemweight: '500 g', material: 'Mesh', SpecialFeature: 'Sole materialThermoplastic Elastomers', About: ' Shoes Upper- These womens shoes feature a breathable mesh upper that keeps your feet cool and comfortable throughout the day. Whether you re at work, college, or having fun, you can wear these shoes for any occasion. They have a lace-less closure that ensures a snug and secure fit. You can also enjoy running, jogging, or walking with these shoes, as they provide great cushioning and support. • Shoes Outsole- With the revolutionary Pillo Foam outsole of these casual shoes for women, experience unmatched comfort and support with every step. The Pillo Foam technology offers impact cushioning and makes your strides more comfortable. Walk with ease all day long, whether running errands or strolling through the city. Elevate your style while prioritizing your comfort with these cool womens shoes. •  Shoes Insole- Embrace the personalized fit offered by the Memory Foam insole of our womens shoes. They perfectly adapt to your foot shape while providing exceptional arch support. Whether walking or running, the cushioned insole guarantees a luxurious and tailor-made experience. These casual shoes are thoughtfully designed to elevate your every step, enhancing support and ensuring an unparalleled stride' },
    { id: 100033, image: '100033.jpg', type: 'secondraw-thirdpart', item: 'Ladies purse', name: 'Lavie Womens Sparkle Ladies Purse Handbag', store: 'Lavie', price: 699, reviews: 1178, deliveringplace: 'Bengaluru', pincode: 560108, add: 'New (2) from 699, Free delivery', discountableprice: 999, warrenty: 1, availability: 'available', brand: 'Lavie', color: 'pink', itemweight: '250 g', material: 'Faux Leather', SpecialFeature: 'oval framed clutch', About: ' This oval framed clutch is made of premium shiny material and It consists of an exclusively imported metal frame , silk lining and a crystal studded clasp. •All Lavie handbag and clutches comes up with Lavie branded lining and clasp closure which can be opened and closed smoothly, built-in pockets,Long Shoulder detachable Metal Chain, large storage capacity which easily carries your basic essentials like a mobile phone, cards, cash, car keys, small wallet, mirror, lipstick and some makeups. • This sparkling style evening purse will add a subtle glow to your evening attire. It always makes you charming and shining, no matter where you are.. • This is the perfect evening bag to any modern woman.It comes with enough space allowing you to quickly access all your essentials.It is an ideal choice for all evening occasions,Best gifts for your girlfriend, wife, lover and friend. Just get this clutch purse to have a wonderful evening ' },

    { id: 100027, image: '100027.jpg', type: 'secondcarousel' },
    { id: 100028, image: '100028.jpg', type: 'secondcarousel' },
    { id: 100029, image: '100029.jpg', type: 'secondcarousel' },
    { id: 100034, image: '100034.jpg', type: 'secondcarousel' },
    { id: 100035, image: '100035.jpg', type: 'secondcarousel' },
    { id: 100036, image: '100036.jpg', type: 'secondcarousel' },
    { id: 100037, image: '100037.jpg', type: 'secondcarousel' },
    { id: 100038, image: '100038.jpg', type: 'secondcarousel' },
    { id: 100039, image: '100039.jpg', type: 'secondcarousel' },
    { id: 100139, image: '100040.jpg', type: 'secondcarousel' },
    { id: 100138, image: '100041.jpg', type: 'secondcarousel' },
    { id: 100137, image: '100037.jpg', type: 'secondcarousel' },
    { id: 100136, image: '100043.jpg', type: 'secondcarousel' },
    { id: 100040, image: '100040.jpg', type: 'secondcarousel' },
    { id: 100041, image: '100041.jpg', type: 'secondcarousel' },
    { id: 100039, image: '100039.jpg', type: 'secondcarousel' },
    { id: 100040, image: '100040.jpg', type: 'secondcarousel' },
    { id: 100041, image: '100041.jpg', type: 'secondcarousel' },

    { id: 100042, image: '100042.jpg', type: 'thirdcarousel' },
    { id: 100142, image: '100142.jpg', type: 'thirdcarousel' },
    { id: 100143, image: '100143.jpg', type: 'thirdcarousel' },
    { id: 100144, image: '100144.jpg', type: 'thirdcarousel' },
    { id: 100145, image: '100145.jpg', type: 'thirdcarousel' },
    { id: 100146, image: '100040.jpg', type: 'thirdcarousel' },
    { id: 100147, image: '100041.jpg', type: 'thirdcarousel' },
    { id: 100148, image: '100037.jpg', type: 'thirdcarousel' },
    { id: 100043, image: '100043.jpg', type: 'thirdcarousel' },
    { id: 100044, image: '100044.jpg', type: 'thirdcarousel' },
    { id: 100045, image: '100045.jpg', type: 'thirdcarousel' },
    { id: 100046, image: '100046.jpg', type: 'thirdcarousel' },
    { id: 100047, image: '100047.jpg', type: 'thirdcarousel' },
    { id: 100048, image: '100048.jpg', type: 'thirdcarousel' },
    { id: 100049, image: '100049.jpg', type: 'thirdcarousel' },
 
    { id: 100050, image: '100050.jpg',type: 'thirddraw-firstpart', item: 'Ladies Purse Handbag', name: 'Lavie Womens Spark Ava Envelope Clutch | Ladies Purse Handbag', store: 'lavie', price: 1139, reviews: 6502, deliveringplace: 'Bengaluru', pincode: 560108, add: 'lavie women sparkle framed clutch ladies purse handbag', discountableprice: 2299, warrenty: 1, availability: 'available', brand: 'lavie', color: 'black', itemweight: '400 g', material: 'Faux Leather', SpecialFeature: 'Closure typeSnap', About: 'The Lavie Spark Ava stylish fold-over clutch is a versatile and functional accessory that effortlessly elevates your evening ensemble with its chic design and practical features •The flap closure of this clutch is equipped with a durable magnet, providing secure storage for your belongings throughout the night. The built-in pockets offer ample space to accommodate all your essentials, keeping them organized and easily accessible • With two compartments, this clutch offers added convenience for efficiently organizing your belongings. It also features a dedicated card holder slot, ensuring quick and convenient access to your cards • The long shoulder detachable metal chain strap provides a hands-free carrying option, allowing you to move with ease and comfort during your evening events' },
    { id: 100051, image: '100051.jpg',type: 'thirddraw-firstpart', item: 'Ladies purse', name: 'Lavie Womens Jazz Framed Clutch | Ladies Purse Handbag', store: 'lavie', price: 899, reviews: 96, deliveringplace: 'Bengaluru', pincode: 560108, add: 'save upto 15% on this product with business princing and Gst input tax credit', discountableprice: 2399, warrenty: 1, availability: 'available', brand: 'lavie', color: 'Black', itemweight: '650 g', material: 'Leather', SpecialFeature: 'Sole materialEthylene Vinyl Acetate', About: ' Textured Material: The textured feel of the material adds an aesthetic element, making this clutch versatile and perfect for any fancy occasion. • Ideal Shape and Size: With dimensions of 20L X 3W X 12H cm, the clutch for women is designed to hold last-minute belongings while offering ample space for essentials during important functions. • Perfect for Evening Occasions: This ladies purse handbag is ideal for all evening occasions and makes an excellent gift for your girlfriend, wife, lover, or friend, ensuring a wonderful evening. •Functional Design: The bag for women features a decent amount of space, a metal top handle, and a clasp closure, combining practicality with elegance.' },
    { id: 100052, image: '100052.jpg',type: 'thirddraw-firstpart', item: 'Ladies Purse Handbag', name: 'TOOBA Handicraft Hand Embroidered Box Clutch Bag Purse for Bridal, Casual, Wedding Bag for Women & Girls', store: 'Tooba', price: 727, reviews: 3209, deliveringplace: 'Bengaluru', pincode: 560108, add: 'save upto 15% on this product with business princing and Gst input tax credit', discountableprice: 1999, warrenty: 1, availability: 'available', brand: 'Campus', color: 'red', itemweight: '500 g', material: 'Synthetic', SpecialFeature: 'Sole materialThermoplastic Elastomers', About: ' Synthetic material sparkling gold colored clutch • 4 inches height x 7 inches length x 2 inches width • Clasp closure • Wipe it with soft cloth, keep away from water and direct sun light. After using it, please store it into dust free bag., do not expose to extreme heat •This sparkling style evening purse will add a subtle glow to your attire. It always makes you charming and shining, no matter where you are.' },
    { id: 100053, image: '100053.jpg',type: 'thirddraw-firstpart', item: 'Ladies purse', name: 'Lavie Womens Sparkle Framed Clutch | Ladies Purse Handbag', store: 'Lavie', price: 699, reviews: 1178, deliveringplace: 'Bengaluru', pincode: 560108, add: 'New (2) from 699, Free delivery', discountableprice: 999, warrenty: 1, availability: 'available', brand: 'Lavie', color: 'pink', itemweight: '250 g', material: 'Faux Leather', SpecialFeature: 'oval framed clutch', About: ' This oval framed clutch is made of premium shiny material and It consists of an exclusively imported metal frame , silk lining and a crystal studded clasp. •All Lavie handbag and clutches comes up with Lavie branded lining and clasp closure which can be opened and closed smoothly, built-in pockets,Long Shoulder detachable Metal Chain, large storage capacity which easily carries your basic essentials like a mobile phone, cards, cash, car keys, small wallet, mirror, lipstick and some makeups. • This sparkling style evening purse will add a subtle glow to your evening attire. It always makes you charming and shining, no matter where you are.. • This is the perfect evening bag to any modern woman.It comes with enough space allowing you to quickly access all your essentials.It is an ideal choice for all evening occasions,Best gifts for your girlfriend, wife, lover and friend. Just get this clutch purse to have a wonderful evening ' },

    
    { id: 100054,  image: '100054.jpg',type: 'thirddraw-secondpart', item: 'Walking Shoe', name: 'Campus Womens Zoe Plus Walking Shoe', store: 'campus', price: 1139, reviews: 6502, deliveringplace: 'Bengaluru', pincode: 560108, add: 'lavie women sparkle framed clutch ladies purse handbag', discountableprice: 2299, warrenty: 1, availability: 'available', brand: 'lavie', color: 'black', itemweight: '400 g', material: 'Faux Leather', SpecialFeature: 'Closure typeSnap', About: ' Shoes Upper- These womens shoes feature a breathable mesh upper that keeps your feet cool and comfortable throughout the day. Whether you re at work, college, or having fun, you can wear these shoes for any occasion. They have a lace-less closure that ensures a snug and secure fit. You can also enjoy running, jogging, or walking with these shoes, as they provide great cushioning and support. • Shoes Outsole- With the revolutionary Pillo Foam outsole of these casual shoes for women, experience unmatched comfort and support with every step. The Pillo Foam technology offers impact cushioning and makes your strides more comfortable. Walk with ease all day long, whether running errands or strolling through the city. Elevate your style while prioritizing your comfort with these cool womens shoes. •  Shoes Insole- Embrace the personalized fit offered by the Memory Foam insole of our womens shoes. They perfectly adapt to your foot shape while providing exceptional arch support. Whether walking or running, the cushioned insole guarantees a luxurious and tailor-made experience. These casual shoes are thoughtfully designed to elevate your every step, enhancing support and ensuring an unparalleled stride' },
    { id: 100055,  image: '100055.jpg',type: 'thirddraw-secondpart', item: 'Walking Shoe', name: 'SPARX Womens Mesh Walking Shoe', store: 'sparx', price: 899, reviews: 96, deliveringplace: 'Bengaluru', pincode: 560108, add: 'save upto 15% on this product with business princing and Gst input tax credit', discountableprice: 2399, warrenty: 1, availability: 'available', brand: 'lavie', color: 'Black', itemweight: '650 g', material: 'Leather', SpecialFeature: 'Sole materialEthylene Vinyl Acetate', About: ' Shoes Upper- These womens shoes feature a breathable mesh upper that keeps your feet cool and comfortable throughout the day. Whether you re at work, college, or having fun, you can wear these shoes for any occasion. They have a lace-less closure that ensures a snug and secure fit. You can also enjoy running, jogging, or walking with these shoes, as they provide great cushioning and support. • Shoes Outsole- With the revolutionary Pillo Foam outsole of these casual shoes for women, experience unmatched comfort and support with every step. The Pillo Foam technology offers impact cushioning and makes your strides more comfortable. Walk with ease all day long, whether running errands or strolling through the city. Elevate your style while prioritizing your comfort with these cool womens shoes. •  Shoes Insole- Embrace the personalized fit offered by the Memory Foam insole of our womens shoes. They perfectly adapt to your foot shape while providing exceptional arch support. Whether walking or running, the cushioned insole guarantees a luxurious and tailor-made experience. These casual shoes are thoughtfully designed to elevate your every step, enhancing support and ensuring an unparalleled stride' },
    { id: 100056,  image: '100056.jpg',type: 'thirddraw-secondpart', item: 'Walking Shoe Handbag', name: 'DOCTOR EXTRA SOFT Lightweight Memory Foam Womens Shoes |', store: 'sparks', price: 727, reviews: 3209, deliveringplace: 'Bengaluru', pincode: 560108, add: 'save upto 15% on this product with business princing and Gst input tax credit', discountableprice: 1999, warrenty: 1, availability: 'available', brand: 'Campus', color: 'red', itemweight: '500 g', material: 'Synthetic', SpecialFeature: 'Sole materialThermoplastic Elastomers', About: ' Shoes Upper- These womens shoes feature a breathable mesh upper that keeps your feet cool and comfortable throughout the day. Whether you re at work, college, or having fun, you can wear these shoes for any occasion. They have a lace-less closure that ensures a snug and secure fit. You can also enjoy running, jogging, or walking with these shoes, as they provide great cushioning and support. • Shoes Outsole- With the revolutionary Pillo Foam outsole of these casual shoes for women, experience unmatched comfort and support with every step. The Pillo Foam technology offers impact cushioning and makes your strides more comfortable. Walk with ease all day long, whether running errands or strolling through the city. Elevate your style while prioritizing your comfort with these cool womens shoes. •  Shoes Insole- Embrace the personalized fit offered by the Memory Foam insole of our womens shoes. They perfectly adapt to your foot shape while providing exceptional arch support. Whether walking or running, the cushioned insole guarantees a luxurious and tailor-made experience. These casual shoes are thoughtfully designed to elevate your every step, enhancing support and ensuring an unparalleled stride' },
    { id: 100057,  image: '100057.jpg',type: 'thirddraw-secondpart', item: 'Walking Shoe', name: 'ASIAN Womens Elasto-02 Knitted,Sports,Walking,Slipon Shoes', store: 'Lavie', price: 699, reviews: 1178, deliveringplace: 'Bengaluru', pincode: 560108, add: 'New (2) from 699, Free delivery', discountableprice: 999, warrenty: 1, availability: 'available', brand: 'Lavie', color: 'pink', itemweight: '250 g', material: 'Faux Leather', SpecialFeature: 'oval framed clutch', About: ' Shoes Upper- These womens shoes feature a breathable mesh upper that keeps your feet cool and comfortable throughout the day. Whether you re at work, college, or having fun, you can wear these shoes for any occasion. They have a lace-less closure that ensures a snug and secure fit. You can also enjoy running, jogging, or walking with these shoes, as they provide great cushioning and support. • Shoes Outsole- With the revolutionary Pillo Foam outsole of these casual shoes for women, experience unmatched comfort and support with every step. The Pillo Foam technology offers impact cushioning and makes your strides more comfortable. Walk with ease all day long, whether running errands or strolling through the city. Elevate your style while prioritizing your comfort with these cool womens shoes. •  Shoes Insole- Embrace the personalized fit offered by the Memory Foam insole of our womens shoes. They perfectly adapt to your foot shape while providing exceptional arch support. Whether walking or running, the cushioned insole guarantees a luxurious and tailor-made experience. These casual shoes are thoughtfully designed to elevate your every step, enhancing support and ensuring an unparalleled stride ' },

    { id: 100058,  image: '100058.jpg',type: 'thirddraw-thirdpart', item: 'Metal Clutch Bag', name: 'Shakuntala Textiles Bridal Womens Antique Brass Purse Ethnic Handmade Metal Clutch Bag', store: 'lavie', price: 1139, reviews: 6502, deliveringplace: 'Bengaluru', pincode: 560108, add: 'lavie women sparkle framed clutch ladies purse handbag', discountableprice: 2299, warrenty: 1, availability: 'available', brand: 'lavie', color: 'black', itemweight: '400 g', material: 'Faux Leather', SpecialFeature: 'Closure typeSnap', About: ' Vintage stone mosaic metal bag with a unique and elegant design • Antique ethnic bridal clutch purse perfect for weddings and special occasions • Features a spacious interior to hold essentials like keys, phone, and makeup • Metal frame and clasp closure ensure security for your belongings' },
    { id: 100059,  image: '100059.jpg',type: 'thirddraw-thirdpart', item: 'Metal Clutch Bag', name: 'For The Beautiful You Neck Embroidered Womens Clutch', store: 'lavie', price: 899, reviews: 96, deliveringplace: 'Bengaluru', pincode: 560108, add: 'save upto 15% on this product with business princing and Gst input tax credit', discountableprice: 2399, warrenty: 1, availability: 'available', brand: 'lavie', color: 'red', itemweight: '650 g', material: 'Leather', SpecialFeature: 'Sole materialEthylene Vinyl Acetate', About: ' Textured Material: The textured feel of the material adds an aesthetic element, making this clutch versatile and perfect for any fancy occasion. • Ideal Shape and Size: With dimensions of 20L X 3W X 12H cm, the clutch for women is designed to hold last-minute belongings while offering ample space for essentials during important functions. • Perfect for Evening Occasions: This ladies purse handbag is ideal for all evening occasions and makes an excellent gift for your girlfriend, wife, lover, or friend, ensuring a wonderful evening. •Functional Design: The bag for women features a decent amount of space, a metal top handle, and a clasp closure, combining practicality with elegance.' },
    { id: 100060,  image: '100060.jpg',type: 'thirddraw-thirdpart', item: 'Metal Clutch Bag', name: 'TOOBA Handicraft Hand Embroidered Box Clutch Bag Purse for Bridal, Casual, Wedding Bag for Women & Girls', store: 'Tooba', price: 727, reviews: 3209, deliveringplace: 'Bengaluru', pincode: 560108, add: 'save upto 15% on this product with business princing and Gst input tax credit', discountableprice: 1999, warrenty: 1, availability: 'available', brand: 'Campus', color: 'blue', itemweight: '500 g', material: 'Velvet', SpecialFeature: 'Sole materialThermoplastic Elastomers', About: ' Synthetic material sparkling gold colored clutch • 4 inches height x 7 inches length x 2 inches width • Clasp closure • Wipe it with soft cloth, keep away from water and direct sun light. After using it, please store it into dust free bag., do not expose to extreme heat •This sparkling style evening purse will add a subtle glow to your attire. It always makes you charming and shining, no matter where you are.' },
    { id: 100061,  image: '100061.jpg',type: 'thirddraw-thirdpart', item: 'Metal Clutch Bag', name: 'Lavie Womens Sparkle Framed Clutch | Ladies Purse Handbag', store: 'Lavie', price: 699, reviews: 1178, deliveringplace: 'Bengaluru', pincode: 560108, add: 'New (2) from 699, Free delivery', discountableprice: 999, warrenty: 1, availability: 'available', brand: 'Lavie', color: 'pink', itemweight: '250 g', material: 'Faux Leather', SpecialFeature: 'oval framed clutch', About: ' This oval framed clutch is made of premium shiny material and It consists of an exclusively imported metal frame , silk lining and a crystal studded clasp. •All Lavie handbag and clutches comes up with Lavie branded lining and clasp closure which can be opened and closed smoothly, built-in pockets,Long Shoulder detachable Metal Chain, large storage capacity which easily carries your basic essentials like a mobile phone, cards, cash, car keys, small wallet, mirror, lipstick and some makeups. • This sparkling style evening purse will add a subtle glow to your evening attire. It always makes you charming and shining, no matter where you are.. • This is the perfect evening bag to any modern woman.It comes with enough space allowing you to quickly access all your essentials.It is an ideal choice for all evening occasions,Best gifts for your girlfriend, wife, lover and friend. Just get this clutch purse to have a wonderful evening ' },
  
    {id: 100062,  image: '100062.jpg',type: 'thirddraw-fourthpart'},

    { id: 100066,  image: '100066.jpg',type: 'fourthcarousel' },
    { id: 100067,  image: '100067.jpg',type: 'fourthcarousel' },
    { id: 100068,  image: '100068.jpg',type: 'fourthcarousel' },
    { id: 100069,  image: '100069.jpg',type: 'fourthcarousel' },
    { id: 100070,  image: '100070.jpg',type: 'fourthcarousel' },
    { id: 100071,  image: '100071.jpg',type: 'fourthcarousel' },
    { id: 100072,  image: '100072.jpg',type: 'fourthcarousel' },
    { id: 100073,  image: '100073.jpg',type: 'fourthcarousel' },
    { id: 100074,  image: '100074.jpg',type: 'fourthcarousel' },
    { id: 100075,  image: '100075.jpg',type: 'fourthcarousel' },
    { id: 100076,  image: '100076.jpg',type: 'fourthcarousel' },
    { id: 100077,  image: '100077.jpg',type: 'fourthcarousel' },
    { id: 100078,  image: '100078',type: 'fourthcarousel' },

    { id: 100082, image: '100082.jpg',type: 'forthraw-firstpart', item: 'stunt car toy', name: 'Wembley Monster Truck Remote Control Car for Kids Rechargeable Rc Car Offroad High Speed with 2 Speeds and 4 Headlight Modes | Lithium Battery | C-Type Charging | Made in India - Red', store: 'wembley', price: 1179, reviews: 1485, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car', discountableprice: 199, warrenty: '6 months', availability: 'available', brand: 'ford', color: 'red', itemweight: '140 g', material: 'plastic', SpecialFeature: 'Experience the excitement with 2 speeds - Normal and Turbo', About: ' bp 1- 🚗 Dual Speed Thrills: Experience the excitement with 2 speeds - Normal and Turbo for versatile off-road adventures. • bp 2- 🎮 Remote Dominance: Command from a distance with the 2.4GHz remote, boasting a range over 75 feet.; ⏰ Extended Playtime: Enjoy over 60 minutes of non-stop action thanks to the in-built lithium battery. • bp 3- 🔌 Effortless Recharging: C-Type rechargeable design with an included cable for convenient and eco-friendly recharging. • bp 4- 💡 Headlights Galore: Navigate with ease using 4 different headlight modes for enhanced visibility. • bp 5- Item Type Name: Toy Car' },
    { id: 100083, image: '100083.jpg',type: 'forthraw-firstpart', item: 'stunt car toy', name: 'Umadiya® Rechargeable Remote Control Sports Car with Openable Doors Rc Car with Led Lights for Kids Super Sports Car for Kids High Speed Rc Car Toy Big Size 3-10 Years Old Kids,Multicolor', store: 'mettle game', price: 989, reviews: 96, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 1999, warrenty: '6 months', availability: 'available', brand: 'lavie', color: 'multicolor', itemweight: '65 g', material: '	plastic', SpecialFeature: ' Experience the excitement with 2 speeds - Normal and Turbo', About: 'The classic card game of matching colors and numbers. Special Action Cards and Wild Cards for unexpected excitement and game-changing fun • Write your own rules for game play with the Customizable Wild cards. Players take turns matching a card in their hand with the color or number of the card shown on the top of the deck.' },
    { id: 100084, image: '100084.jpg',type: 'forthraw-firstpart', item: 'stunt car toy', name: 'Zest 4 Toyz Remote Control Car For Kids With Mist Smoke Effect 2 Wd Monster Truck Rock Crawler Climbing Rc Toy Vehicle Car For Boys And Girls-Black', store: 'mettle game', price: 89, reviews: 3209, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 199, warrenty: 1, availability: 'available', brand: 'Campus', color: 'multicolor', itemweight: '50 g', material: '	plastic', SpecialFeature: ' Experience the excitement with 2 speeds - Normal and Turbo', About: 'The classic card game of matching colors and numbers. Special Action Cards and Wild Cards for unexpected excitement and game-changing fun • Write your own rules for game play with the Customizable Wild cards. Players take turns matching a card in their hand with the color or number of the card shown on the top of the deck.' },
    { id: 100085, image: '100085.jpg',type: 'forthraw-firstpart', item: 'stunt car toy', name: 'Popsugar Off Roader Rechargeable Remote Control Car | Monster Truck with 2 Speeds | 4 Headlight Modes | Lithium Battery | C-Type Charging | Remote Control Car for Kids | Made in India, Red', store: 'mettle game', price: 99, reviews: 1178, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 199, warrenty: 1, availability: 'available', brand: 'Lavie', color: 'multicolor', itemweight: '50 g', material: '	plastic', SpecialFeature: ' Experience the excitement with 2 speeds - Normal and Turbo', About: ' The classic card game of matching colors and numbers. Special Action Cards and Wild Cards for unexpected excitement and game-changing fun • Write your own rules for game play with the Customizable Wild cards. Players take turns matching a card in their hand with the color or number of the card shown on the top of the deck.' },
  
    { id: 100086,  image: '100086.jpg',type: 'forthraw-secondpart', item: 's23 ultra case', name: 'DIZORO Samsung S23 Ultra Case, Compatible with Mag Safe, Non-Yellow Military-Grade Drop Protection & Hard PC Back Cover Slim Transparent Anti-Scratch Shockproof Phone Case (Mag Safe Black)', store: 'disore', price: 139, reviews: 6502, deliveringplace: 'Bengaluru', pincode: 560108, add: 'ringke onyx compatible with samsung galaxy s23 ultra  5g case', discountableprice: 299, warrenty: 1, availability: 'available', brand: 'dizore', color: 'Magsafe Black', itemweight: '100 g', material: 'plastic', SpecialFeature: ' Magnetic MagSafe', About: ' Magnetic MagSafe' },
    { id: 100087,  image: '100087.jpg',type: 'forthraw-secondpart', item: 's23 ultra case', name: 'VIDO Exclusive Soft Back Case Cover for Samsung Galaxy S23 Ultra 5G(Shock Proof |360 Degree Complete Protection)', store: 'mettle game', price: 99, reviews: 96, deliveringplace: 'Bengaluru', pincode: 560108, add: 'ringke onyx compatible with samsung galaxy s23 ultra  5g case ', discountableprice: 399, warrenty: 1, availability: 'available', brand: 'lavie', color: 'multicolor', itemweight: '65 g', material: '	plastic', SpecialFeature: 'Magnetic MagSafe', About: '• Magnetic MagSafe' },
    { id: 100088,  image: '100088.jpg',type: 'forthraw-secondpart', item: 's23 ultra case', name: 'Spigen Neo Hybrid Back Cover Case Compatible with Galaxy S23 Ultra (TPU + Poly Carbonate | Gunmetal)', store: 'mettle game', price: 89, reviews: 3209, deliveringplace: 'Bengaluru', pincode: 560108, add: 'ringke onyx compatible with samsung galaxy s23 ultra  5g case ', discountableprice: 199, warrenty: 1, availability: 'available', brand: 'Campus', color: 'multicolor', itemweight: '50 g', material: '	Cardstock', SpecialFeature: ' Magnetic MagSafe', About: '• Magnetic MagSafe' },
    { id: 100089,  image: '100089.jpg',type: 'forthraw-secondpart', item: 's23 ultra case', name: 'Ringke Fusion-X Compatible with Samsung Galaxy S23 Ultra 5G Case Cover Military Camo Hard Back Soft TPU Bumper Scratch Resistant Shockproof Protection Samsung S23 Ultra Back Cover - Camo Black', store: 'mettle game', price: 99, reviews: 1178, deliveringplace: 'Bengaluru', pincode: 560108, add: 'ringke onyx compatible with samsung galaxy s23 ultra  5g case ', discountableprice: 199, warrenty: 1, availability: 'available', brand: 'Lavie', color: 'multicolor', itemweight: '50 g', material: '	Cardstock', SpecialFeature: ' Magnetic MagSafe', About: ' Magnetic MagSafe' },
   
    { id: 100090,image: '100090.jpg', type: 'forthraw-thirdpart', item: 'penguin toy', name: 'Amazon Brand - Jam & Honey Soft Penguin Plush Toy for Kids | Soft Toy for Boys and Girls | Super-Soft and Safe| Ideal for Gifting | Height 17 cm | Black and White', store: 'amzon brand', price: 179, reviews: 85, deliveringplace: 'Bengaluru', pincode: 560108, add: 'tyyshine dancing duck with music', discountableprice: 199, warrenty: '6 months', availability: 'available', brand: 'ford', color: 'black and white', itemweight: '140 g', material: 'soft plush toy', SpecialFeature: 'excellent gift or return gift for baby boys and girls', About: ' Cuddles and giggles, hugs and snuggles! Add fun to your babys playtime with this adorable plush penguin from Jam & Honey. It is perfectly sized, soft, and safe for your little one • Super soft: It is made from super-soft, skin-friendly material so that your baby can enjoy the toy safely • Safe: It is BIS-approved and tested according to IS 9873 standards • Huggable: Your little one will love cuddling this cute, soft plush toy • Gifting: It makes an excellent gift or return gift for baby boys and girls' },
    { id: 100091,image: '100091.jpg', type: 'forthraw-thirdpart', item: 'rolling and swirling ramb drop toy', name: 'Amazon Brand - Jam & Honey | Rolling and Swirling Ramp Drop Toy for Kids | 5 Layers. 4 Balls', store: 'amazone', price: 309, reviews: 96, deliveringplace: 'Bengaluru', pincode: 560108, add: 'amazon brand jam&honey soft toy ', discountableprice: 999, warrenty: '6 months', availability: 'available', brand: 'lavie', color: 'multicolor', itemweight: '65 g', material: '	plastic', SpecialFeature: 'helps children to develop their number skills ', About: ' Helps learn counting - The ball drop tower helps children to develop their number skills by encouraging them to count and match the colorful balls as they roll down the tower run. • Helps learn color recognition - The multicolored design of the toy helps children to improve their color recognition by teaching them to distinguish between different colors. • Easy to assemble and breakdown, making playtime a breeze while on-the-go. • Weighted balls rattle when shaken, adding to the entertainment value. • Weighted balls rattle when shaken, adding to the entertainment value.' },
    { id: 100092,image: '100092.jpg', type: 'forthraw-thirdpart', item: 'chess', name: 'Amazon Brand - Jam & Honey Wooden Handcrafted Chess | Great Birthday Gift | Toy for Kids Girls Boys', store: 'mettle game', price: 89, reviews: 209, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 199, warrenty: 1, availability: 'available', brand: 'Campus', color: 'multicolor', itemweight: '50 g', material: '	plastic', SpecialFeature: ' Crafted from durable, premium wood, ', About: 'The classic card game of matching colors and numbers. Special Action Cards and Wild Cards for unexpected excitement and game-changing fun • Write your own rules for game play with the Customizable Wild cards. Players take turns matching a card in their hand with the color or number of the card shown on the top of the deck.' },
    { id: 100093,image: '100093.jpg', type: 'forthraw-thirdpart', item: 'tablesoccer', name: 'Amazon Brand - Jam & Honey Foosball (Big) | Table Soccer Game for Adults/Kids - Indoor Sport Multicolor', store: 'mettle game', price: 1999, reviews: 1178, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 2999, warrenty: 1, availability: 'available', brand: 'Lavie', color: 'multicolor', itemweight: '50 g', material: '	plastic', SpecialFeature: ' Experience the excitement with 2 speeds - Normal and Turbo', About: 'The classic card game of matching colors and numbers. Special Action Cards and Wild Cards for unexpected excitement and game-changing fun • Write your own rules for game play with the Customizable Wild cards. Players take turns matching a card in their hand with the color or number of the card shown on the top of the deck.' },
   
    {id: 100094, image: '100062.jpg',type: 'forthraw-fourthpart'},
   
    { id: 100095, image: '100095.jpg',type: 'sixthcarousel' },
    { id: 100096, image: '100096.jpg',type: 'sixthcarousel' },
    { id: 100195, image: '100195.jpg',type: 'sixthcarousel' },
    { id: 100196, image: '100196.jpg',type: 'sixthcarousel' },
    { id: 100097, image: '100097.jpg',type: 'sixthcarousel' },
    { id: 100098, image: '100098.jpg',type: 'sixthcarousel' },
    { id: 100099, image: '100098.jpg',type: 'sixthcarousel' },
    { id: 100100, image: '100100.jpg',type: 'sixthcarousel' },
    { id: 100101, image: '100101.jpg',type: 'sixthcarousel' },
    { id: 100102, image: '100102.jpg',type: 'sixthcarousel' },
    { id: 100103, image: '100103.jpg',type: 'sixthcarousel' },
    { id: 100104, image: '100104.jpg',type: 'sixthcarousel' },
    { id: 100105, image: '100105.jpg',type: 'sixthcarousel' },
 
    { id: 100106, image: '100106.jpg',type: 'fifthraw-firstpart', item: 'home decoration',title: 'ArtX Paper Madhubani Art Paintings with Frame for Home Decor, Wall Painting for Living Room, Multicolor, Natural Wood Color Frames, Set of 4',      name: 'The Castle Decor Golden Deer Wall Painting for Living Room, Bedroom, Hotels - Big Size Wooden Framed 27x48 Stunning Wall Art for Home Decoration, Perfect Wall Decor for Living Rooms and Bedrooms.', store: 'castle decore ', price: 2199, reviews: 1485, deliveringplace: 'Bengaluru', pincode: 560108, add: 'The castle decor radha krishnan painting with frame 5 big size', discountableprice: 5499,material: 'Polyester', warrenty: '6 months', availability: 'available', brand: 'ford', color: 'red', itemweight: '5 kg', SpecialFeature: '3D wall art', About: ' **Elegant Wall Decor for Living Rooms:** Transform your space with this stunning Castle Decor Golden Deer Digital Wall Painting, a perfect addition to any home wall art collection. Ideal as a big painting with frame for living rooms, its intricate detailing promises to captivate all who enter. • **Versatile Painting for Wall Decoration:** Whether you pair it with Buddha paintings or 3D wall art for the living room, this large wooden-framed piece seamlessly blends with various wall decors, including seven horses Vastu paintings and Radha Krishna wall decor themes. • **Luxurious Wall Art for Bedrooms and Hotels:** Elevate your rooms ambiance with this premium 27xGolden Deer wall painting. Its a statement piece that complements both modern and traditional wall arts for home decoration, creating an inviting atmosphere in bedrooms or hotels. •  **Exclusive Big Wall Art:** The grand-scale design makes it one of the finest big wall paintings for living rooms, offering a focal point that harmonizes beautifully with other elements like shivaji maharaj photo frame big size or hanging running horses Vastu frames.' },
    { id: 100107, image: '100107.jpg',type: 'fifthraw-secondpart', title:'Indiglam Styles V-Neck Sleeveless Floral Wrap Regular Jumpsuit for Women Swag Womens Soft Jumpsuits Miss Chase Womens Wine V-Neck',item: 'womens v neck sleeveless jumpsuit', name: 'Vivvli Womens Polyester A-line V-Neck Bishop Sleeve Midi Belted Dress', store: 'vivvli', price: 798, reviews: 96, deliveringplace: 'Bengaluru', pincode: 560108, add: 'miss chase womens off white solid regular length ', discountableprice: 1999, warrenty: '6 months', availability: 'available', brand: 'vvivvle', color: 'multicolor', itemweight: '165 g', material: 'Polyester', SpecialFeature: 'Fabric: 95% Polyester,', About: ' Fabric: 95% Polyester, 5% Spandex; Style: A-line midi-maxi Belted Dress • Pattern: Solid/Plain | Closure: Zip | Type: A-line | Neckline: V Neck | Sleeve type: Bishop Sleeve | Sleeve length: Long Sleeve | Waist line: High Waist | Hem Shaped: Flared • OCCASIONS: Perfect to be a little cocktail dress for party or wedding event. It is also suitable for night clubbing, dating, birthday ,wedding,engagement and prom occasions as an elegant dress, a unique party dress • There might be slight color variation between the actual product and image shown on the screen due to photoshoot lighting' },
    
    { id: 100108, image: '100108.jpg',type: 'fifthraw-thirdpart', item: 'Cushion',title:'',name: 'TheYaYaCafe Christmas Cushion Covers for House Decoration 12 x 12 Inches with Filler', store: 'yayacafe', price: 89, reviews: 450, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 799, warrenty: 1, availability: 'available', brand: 'Campus', color: 'multicolor', itemweight: '50 g', material: '	Velvet', SpecialFeature: 'Fabric: Premium quality Canvas cotton', About: ' Gift set contents - 1 Cushion Cover for Christmas • Details for Cushion Cover- Fabric: Premium quality Canvas cotton, Color fastness of fabric and print - 100%, Closure: Flap at back • Gift Suggestions: Christmas Gifts, New Year 2023 Gifts, Christmas and New Year 2023 Cushion, Christmas and New Year Gifts for kids, friends, family,clients, employees, office staff.' },
    { id: 101008, image: '101008.jpg',type: 'fifthraw-thirdpart', item: 'Cushion',title:'',name: 'TheYaYaCafe Christmas Cushion Covers for House Decoration 12 x 12 Inches with Filler', store: 'yayacafe', price: 89, reviews: 450, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 799, warrenty: 1, availability: 'available', brand: 'Campus', color: 'multicolor', itemweight: '50 g', material: '	Velvet', SpecialFeature: 'Fabric: Premium quality Canvas cotton', About: ' Gift set contents - 1 Cushion Cover for Christmas • Details for Cushion Cover- Fabric: Premium quality Canvas cotton, Color fastness of fabric and print - 100%, Closure: Flap at back • Gift Suggestions: Christmas Gifts, New Year 2023 Gifts, Christmas and New Year 2023 Cushion, Christmas and New Year Gifts for kids, friends, family,clients, employees, office staff.' },
    { id: 101009, image: '101009.jpg',type: 'fifthraw-thirdpart', item: 'Cushion', title:'TIED RIBBONS Christmas Decorations Items Cushion Cover ',  name: 'TheYaYaCafe Christmas Cushion Covers for House Decoration 12 x 12 Inches with Filler', store: 'yayacafe', price: 89, reviews: 450, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 799, warrenty: 1, availability: 'available', brand: 'Campus', color: 'multicolor', itemweight: '50 g', material: '	Velvet', SpecialFeature: 'Fabric: Premium quality Canvas cotton', About: ' Gift set contents - 1 Cushion Cover for Christmas • Details for Cushion Cover- Fabric: Premium quality Canvas cotton, Color fastness of fabric and print - 100%, Closure: Flap at back • Gift Suggestions: Christmas Gifts, New Year 2023 Gifts, Christmas and New Year 2023 Cushion, Christmas and New Year Gifts for kids, friends, family,clients, employees, office staff.' },
    { id: 101010, image: '101010.jpg',type: 'fifthraw-thirdpart', item: 'Cushion', title:'TheYaYaCafe Christmas Gifts Cushion Covers',  name: 'TheYaYaCafe Christmas Cushion Covers for House Decoration 12 x 12 Inches with Filler', store: 'yayacafe', price: 89, reviews: 450, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 799, warrenty: 1, availability: 'available', brand: 'Campus', color: 'multicolor', itemweight: '50 g', material: '	Velvet', SpecialFeature: 'Fabric: Premium quality Canvas cotton', About: ' Gift set contents - 1 Cushion Cover for Christmas • Details for Cushion Cover- Fabric: Premium quality Canvas cotton, Color fastness of fabric and print - 100%, Closure: Flap at back • Gift Suggestions: Christmas Gifts, New Year 2023 Gifts, Christmas and New Year 2023 Cushion, Christmas and New Year Gifts for kids, friends, family,clients, employees, office staff.' },

    { id: 100109, image: '100109.jpg',type: 'fifthraw-fourthpart', title: 'ArtX Paper Madhubani Art Paintings with Frame for Home Decor, Wall Painting for Living Room, Multicolor, Natural Wood Color Frames, Set of 4' ,     item: 'painting', name: 'SAF paintings Set of 3 Flower Floral Pot UV Coated Home Decorative Gift Item Framed Painting 13.5 inch X 22 inch SANFSW4951', store: 'saf', price: 272, reviews: 78, deliveringplace: 'Bengaluru', pincode: 560108, add: 'goooyo GY-9798 Rechargeable remote control thar toy car ', discountableprice: 699, warrenty: 1, availability: 'available', brand: 'Lavie', color: 'multicolor', itemweight: '500 g', material: '	wood', SpecialFeature: 'High quality synthetic in framing.', About: ' Usage : It can be used for Living room , Home décor and for gifting purposes. • Package contains : Three UV Textured Print Framed Painting without glass ' },
  
    { id: 100110, image: '100110.jpg',type: 'seventhcarousel' },
    { id: 100111, image: '100111.jpg',type: 'seventhcarousel' },
    { id: 100112, image: '100112.jpg',type: 'seventhcarousel' },
    { id: 100113, image: '100113.jpg',type: 'seventhcarousel' },
    { id: 100114, image: '100114.jpg',type: 'seventhcarousel' },
    { id: 100115, image: '100115.jpg',type: 'seventhcarousel' },
    { id: 100116, image: '100116.jpg',type: 'seventhcarousel' },
    { id: 100117, image: '100117.jpg',type: 'seventhcarousel' },
    { id: 100118, image: '100118.jpg',type: 'seventhcarousel' },
    { id: 100119, image: '100119.jpg',type: 'seventhcarousel' },
    { id: 100120, image: '100120.jpg',type: 'seventhcarousel' },
    { id: 100121, image: '100121.jpg',type: 'seventhcarousel' },
    { id: 100122, image: '100122.jpg',type: 'seventhcarousel' },
    { id: 100123, image: '100123.jpg',type: 'seventhcarousel' },
    { id: 100124, image: '100124.jpg',type: 'seventhcarousel' },
  ]
  getflatarray() {
    for (let i = 0; i < this.productdetails.length; i++) {
      const item = this.productdetails[i];
      this.flatobj[`id_${item.id}`] = item;
    }
    return this.flatobj;

  }
  serchingid(id: any) {
    for (let i = 0; i < this.productdetails.length; i++) {
      if (this.productdetails[i].id === id) {
        return this.productdetails[i]
      }
    }
    return null
  }
  
  buynowdata(data:any){
    const buydata=data;
    console.log('shippingaddress in service',buydata);
    
    localStorage.setItem('buynowdata',JSON.stringify(buydata))
    // localStorage.clear();
  }

  constructor() { }
  


}
